# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114DFVYOVudCxEP90mcmNuM06uump4EUh
"""

# Idea:
# This code generates a simulated dataset representing revenue, cost, units sold, and customers for each month of the year.
# The dataset is used to create visualizations that explore the relationships between these variables, including:
# 1. A line plot showing revenue and cost per month.
# 2. A scatter plot between revenue and units sold.
# 3. A bar plot showing the number of customers per month.
# 4. A heatmap displaying the relationships between the variables.
# 5. A box plot showing the distribution of revenue per month.


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Step 1: Create a simulated dataset with more data
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

data = {
    'Month': months,
    'Revenue': np.random.randint(10000, 50000, size=12),
    'Cost': np.random.randint(5000, 20000, size=12),
    'Units Sold': np.random.randint(300, 1000, size=12),
    'Customers': np.random.randint(1000, 5000, size=12)
}

df = pd.DataFrame(data)

# Step 2: Visualize revenue and cost per month
plt.figure(figsize=(10, 6))
plt.plot(df['Month'], df['Revenue'], label='Revenue', color='blue', marker='o')
plt.plot(df['Month'], df['Cost'], label='Cost', color='red', marker='s')
plt.title('Revenue and Cost per Month')
plt.xlabel('Month')
plt.ylabel('Amount (VND)')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Step 3: Scatter plot between Revenue and Units Sold
plt.figure(figsize=(8, 6))
sns.scatterplot(x='Units Sold', y='Revenue', data=df, color='green', s=100, marker='D')
plt.title('Scatter Plot: Revenue vs Units Sold')
plt.xlabel('Units Sold')
plt.ylabel('Revenue (VND)')
plt.tight_layout()
plt.show()

# Step 4: Bar plot showing the number of customers per month
plt.figure(figsize=(10, 6))
sns.barplot(x='Month', y='Customers', data=df, palette='coolwarm', hue='Month')  # Added hue='Month'
plt.title('Number of Customers per Month')
plt.xlabel('Month')
plt.ylabel('Customers')
plt.tight_layout()
plt.show()

# Step 5: Heatmap of relationships between variables
plt.figure(figsize=(8, 6))
sns.heatmap(df.drop('Month', axis=1).corr(), annot=True, cmap='coolwarm', vmin=-1, vmax=1)
plt.title('Heatmap of Relationships Between Variables')
plt.tight_layout()
plt.show()

# Step 6: Box plot to see the distribution of revenue per month
plt.figure(figsize=(8, 6))
sns.boxplot(x='Month', y='Revenue', data=df, palette='Set2', hue='Month')  # Added hue='Month'
plt.title('Box Plot of Revenue per Month')
plt.xlabel('Month')
plt.ylabel('Revenue (VND)')
plt.tight_layout()
plt.show()